### ISSUE TITLE
Problems with MediaWikia 1.32 CentOS 7.x PHP 7.2 from centos-release-scl repo and Active Directory

### ISSUE THREAD

**Issue by Deicidium2666** [shanept/mediawiki-LdapAuth#11]
Hello partners

I have been trying to configure authentication with Active Directory and I could not achieve it

This is the configuration of my file /var/www/html/mediawiki/LocalSettings.php

wfLoadExtension ('LdapAuth');
$ wgLdapAuthDomainNames = 'FOO.LOCAL';
$ wgLdapAuthServers = '192.168.0.1';
$ wgLdapAuthBindDN = 'fooaccount@FOO.LOCAL';
$ wgLdapAuthBindPass = 'foopassword';
$ wgLdapAuthIsActiveDirectory = true;

and when I try to authenticate I just get the error

[XNtsVFxeuxQZiymEsXdDxwAAAAI] 2019-05-15 01:33:08: Fatal exception of type "Error"

and the most mysterious thing is that the time is not correct despite configuring the php.ini and the LocalSettings.php file

**Comment by shanept** [comment]
Hi Deicidium2666,

Unfortunately I'm going to need more information in order to assist you with this issue.

Did your error output produce any backlogging? If not, could you please configure PHP to produce errors? For more info: https://m.mediawiki.org/wiki/Manual:How_to_debug

Kind regards,
Shane Thompson

**Comment by Deicidium2666** [comment]
Hi I figured out. Instructions in Spanish :

Instalamos la compatibilidad de PHP 7.2 con LDAP:

yum install -y rh-php72-php-ldap

Ingresamos al directorio base de la instalación de MediaWiki:

cd /var/www/html/mediawiki/

Descargamos el script de instalación de Composer:

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

Hacemos la comprobación de la integridad del instalador de Composer:

php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

Instalamos Composer en el directorio:

php /var/www/html/mediawiki/composer-setup.php

Instalamos el componente de LDAP de Symfony:

/var/www/html/mediawiki/composer.phar require symfony/ldap

Descargamos el Plugin de autenticacion de LDAP para MediaWiki:

wget https://github.com/shanept/mediawiki-LdapAuth/archive/master.zip -O /var/www/html/mediawiki/extensions/master.zip

Entramos al directorio de las extensiones de MediaWiki:

cd /var/www/html/mediawiki/extensions/

Descompromimos el plugin:

unzip master.zip

Debemos el borrar el archivo comprimido:

rm -f /var/www/html/mediawiki/extensions/master.zip

Cambiamos el nombre del directorio descomprimidos:

mv /var/www/html/mediawiki/extensions/mediawiki-LdapAuth-master/ /var/www/html/mediawiki/extensions/LdapAuth/

Ingresamos al directorio del plugin de LDAP:

cd /var/www/html/mediawiki/extensions/LdapAuth/

Descargamos el script de instalación de Composer:

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

Hacemos la comprobación de la integridad del instalador de Composer:

php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

Instalamos Composer en el directorio:

php /var/www/html/mediawiki/extensions/LdapAuth/composer-setup.php

Hacemos la instalaciones de las dependencias del Plugin de LDAP para MediaWiki:

/var/www/html/mediawiki/extensions/LdapAuth/composer.phar install --no-dev

Editamos la configuración de MediaWiki:

vim /var/www/html/mediawiki/LocalSettings.php

Agregamos al final el siguiente contenido:

#Set Default Timezone                                                                                                                                                                                                                      
$wgLocaltimezone = "America/Bogota";                                                                                                                                                                                                       
date_default_timezone_set( $wgLocaltimezone );                                                                                                                                                                                             
                                                                                                                                                                                                                                           
#Trazado de errores                                                                                                                                                                                                                        
error_reporting( -1 );                                                                                                                                                                                                                     
ini_set( 'display_errors', 1 );                                                                                                                                                                                                            
$wgShowExceptionDetails = true;                                                                                                                                                                                                            
$wgShowDBErrorBacktrace = true;                                                                                                                                                                                                            
                                                                                                                                                                                                                                           
#Configuracion LDAP (Active Directory) FOO COMPANY                                                                                                                                                                                               
wfLoadExtension( 'LdapAuth' );                                                                                                                                                                                                             
$wgLdapAuthDomainNames = 'FOO.LOCAL';                                                                                                                                                                                                   
$wgLdapAuthServers = '192.168.0.2, 192.168.0.3';                                                                                                                                                                                                         
$wgLdapAuthBindDN = 'CN=s-mediawiki,OU=MediaWiki,OU=Cuentas de Servicio,OU=FOO Company,DC=FOO,DC=LOCAL';                                                                                                       
$wgLdapAuthBindPass = '9%V67)+]JQ123456';                                                                                                                                                                                                    
$wgLdapAuthIsActiveDirectory = true;                                                                                                                                                                                                       
$wgLdapAuthRequireDomain = true;                                                                                                                                                                                                           
$wgLdapAuthUseLocal = true;                                                                                                                                                                                                                
$wgLdapAuthBaseDN = 'DC=FOO,DC=LOCAL';                                                                                                                                                                                                  
$wgGroupPermissions['*']['autocreateaccount'] = true;

Guardamos el archivo y cerramos el editor.

Cambiamos los permisos al directorio raíz de Apache:

chown -R apache:apache /var/www/html/

Reiniciamos el servidor Apache HTTP Server:

systemctl restart httpd.service


= Bibliografía =

* https://github.com/shanept/mediawiki-LdapAuth/
