### ISSUE TITLE
Fatal error when connecting with LDAP

### ISSUE THREAD

**Issue by Didou31** [shanept/mediawiki-LdapAuth#2]
Hi,

There is an error in exception file MappingException.php which inherits from ConfigException: there is a double call to I18nTrait which cause an error (call to parent constructor is wrong)

Here is ConfigException.php
<?php
namespace Shanept\LdapAuth\Exceptions;

use ConfigException as CeBase;

class ConfigException extends CeBase implements I18nException {
        use I18nTrait;
}

=> We must remove use I18nTrait; from MappingException.php in order to do the call to parent constructor.

See you
:+)

**Comment by shanept** [comment]
Well you've got an eagle eye - thanks for that one!
