### ISSUE TITLE
[AD] Error at login

### ISSUE THREAD

**Issue by Clapiote** [shanept/mediawiki-LdapAuth#9]
Hi,
I got an error when log in to mediawiki, with AD authentication. But the authentication works fine, I'm logged in if I go to another page or refresh the page.

[6097cfd71bb697126e7212c6] /index.php?title=Sp%C3%A9cial:Connexion&returnto=Accueil Shanept\LdapAuth\Exceptions\MappingException from line 108 of /var/www/mediawiki/extensions/LdapAuth/src/Groups/LdapGroupSync.php: No domain found for "vincent".

Backtrace:

#0 /var/www/mediawiki/extensions/LdapAuth/src/Groups/LdapGroupSync.php(93): Shanept\LdapAuth\Groups\LdapGroupSync->populateGroups()
#1 /var/www/mediawiki/extensions/LdapAuth/src/Auth/PrimaryAuthenticationProvider.php(188): Shanept\LdapAuth\Groups\LdapGroupSync->map()
#2 /var/www/mediawiki/includes/auth/AuthManager.php(2441): Shanept\LdapAuth\Auth\PrimaryAuthenticationProvider->postAuthentication(User, MediaWiki\Auth\AuthenticationResponse)
#3 /var/www/mediawiki/includes/auth/AuthManager.php(694): MediaWiki\Auth\AuthManager->callMethodOnProviders(integer, string, array)
#4 /var/www/mediawiki/includes/auth/AuthManager.php(383): MediaWiki\Auth\AuthManager->continueAuthentication(array)
#5 /var/www/mediawiki/includes/specialpage/AuthManagerSpecialPage.php(353): MediaWiki\Auth\AuthManager->beginAuthentication(array, string)
#6 /var/www/mediawiki/includes/specialpage/AuthManagerSpecialPage.php(482): AuthManagerSpecialPage->performAuthenticationStep(string, array)
#7 /var/www/mediawiki/includes/htmlform/HTMLForm.php(665): AuthManagerSpecialPage->handleFormSubmit(array, VFormHTMLForm)
#8 /var/www/mediawiki/includes/specialpage/AuthManagerSpecialPage.php(416): HTMLForm->trySubmit()
#9 /var/www/mediawiki/includes/specialpage/LoginSignupSpecialPage.php(317): AuthManagerSpecialPage->trySubmit()
#10 /var/www/mediawiki/includes/specialpage/SpecialPage.php(569): LoginSignupSpecialPage->execute(NULL)
#11 /var/www/mediawiki/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#12 /var/www/mediawiki/includes/MediaWiki.php(288): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#13 /var/www/mediawiki/includes/MediaWiki.php(860): MediaWiki->performRequest()
#14 /var/www/mediawiki/includes/MediaWiki.php(517): MediaWiki->main()
#15 /var/www/mediawiki/index.php(42): MediaWiki->run()
#16 {main}

It's like no domain was specified for the object user.
The domain is selected with the select menu.
I use mediawiki 1.32 and my configuration is :

wfLoadExtension( 'LdapAuth' );
$wgLdapAuthDomainNames = 'FOO.LAB';
$wgLdapAuthServers = 'dc.foo.lab';
$wgLdapAuthBindDN = 'FOO\mediawiki';
$wgLdapAuthBindPass = <password>;
$wgLdapAuthIsActiveDirectory = true;
$wgLdapAuthRequireDomain = true;
$wgLdapAuthBaseDN = "dc=FOO,dc=LAB";

Thanks,
Vincent

**Comment by kmix** [comment]
@Clapiote I ran into this issue as well this week and have submitted a PR with the workarounds I implemented. Hoping for something better long-term, but in the meantime feel free to do a pull on my fork.

**Comment by shanept** [comment]
Hi @Clapiote 

I have merged the changes into the master branch. Could you please give it a shot and see if this fixes your issue?

**Comment by Clapiote** [comment]
Yes it works now, thanks !
